"""Graph storage abstraction (Step 8) — the seam that keeps LexiMind graph-DB-agnostic.

The builder/service depend on this `GraphStore` Protocol, NOT on SQLAlchemy. The Module-1 implementation
is `GraphRepository` (SQL rows + JSON provenance) which satisfies this Protocol structurally; a future
Neo4j / Apache AGE / Memgraph backend implements the SAME methods and drops in via dependency injection
with no builder/service change.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from app.knowledge.models import GraphConstructionLog, GraphEntity, GraphRelationship


class GraphStore(Protocol):
    # entities
    def workspace_entities(self, workspace_id: str, owner_id: str, *, active_only: bool = True) -> List[GraphEntity]: ...
    def add_entity(self, entity: GraphEntity) -> GraphEntity: ...
    def update_entity(self, entity: GraphEntity) -> GraphEntity: ...
    def get_entity(self, entity_id: str, owner_id: str) -> Optional[GraphEntity]: ...
    def search_entities(self, workspace_id: str, owner_id: str, *, query: Optional[str] = None,
                        entity_type: Optional[str] = None, limit: int = 50) -> List[GraphEntity]: ...

    # relationships
    def add_relationship(self, rel: GraphRelationship) -> GraphRelationship: ...
    def update_relationship(self, rel: GraphRelationship) -> GraphRelationship: ...
    def find_relationship(self, workspace_id: str, source_id: str, target_id: str,
                          rel_type: str) -> Optional[GraphRelationship]: ...
    def relationships_for(self, workspace_id: str, entity_id: str) -> List[GraphRelationship]: ...

    # telemetry + metrics
    def save_log(self, log: GraphConstructionLog) -> GraphConstructionLog: ...
    def metrics(self, workspace_id: str) -> Dict[str, Any]: ...
    def commit(self) -> None: ...
