"""Note ORM models — Phase 3, Module 6: Smart Notes Engine.

Five NEW tables (created by `create_all`, no migration — the schema is young and additive):

- `Note`          — a persistent, editable, user-owned knowledge asset. Unlike a Summary (a
                    read-only AI output), a Note is a first-class document the user keeps editing.
- `NoteSection`   — the structural outline produced at AI-generation time (heading + body,
                    ordered). Used to seed the editable `Note.content` and to drive regeneration.
- `NoteCitation`  — grounded provenance (Workspace → Document → Page → Chunk). Keyed to the
                    NOTE (not the section) so free-form editing of `content` never orphans a
                    citation reference.
- `Tag`           — a workspace-scoped label (name + color) reusable across notes.
- `NoteTag`       — the many-to-many association between notes and tags.

Design mirrors the summaries/chat modules: structured rows in SQLite, evidence/vectors in FAISS.
An AI note is generated by REUSING the retrieval + context pipeline (never by feeding whole
documents to the LLM), so every generated section carries the citations Phase 2 preserved.

`Note.content` is the canonical, editable body (Markdown). The editor reads/writes it directly;
autosave bumps `version` for optimistic-concurrency conflict detection. `NoteSection` rows are a
snapshot of the AI's structure — the live outline the UI renders is derived from the headings in
`content`, so it stays correct after the user edits.

Future-proofing (columns present, features NOT implemented): version history
(`version`, `parent_note_id`), collaboration/comments/shared/linked notes (`owner_id` is real,
`document_id`/`conversation_id`/`source` record provenance for back-links), folders
(`folder_id`).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, DateTime, Float, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _note_id() -> str:
    return f"note_{uuid.uuid4().hex[:16]}"


def _sec_id() -> str:
    return f"nsec_{uuid.uuid4().hex[:16]}"


def _cit_id() -> str:
    return f"ncit_{uuid.uuid4().hex[:16]}"


def _tag_id() -> str:
    return f"tag_{uuid.uuid4().hex[:16]}"


class Note(Base):
    __tablename__ = "notes"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_note_id)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    owner_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    # Provenance / back-links (all nullable — a blank note has none).
    document_id: Mapped[str | None] = mapped_column(String(40), index=True, default=None)     # source Document row id
    document_ids: Mapped[list | None] = mapped_column(JSON, default=None)                     # multi-doc AI scope
    scope: Mapped[str] = mapped_column(String(20), nullable=False, default="document")        # document|multi|workspace
    conversation_id: Mapped[str | None] = mapped_column(String(40), default=None)             # source chat conversation
    folder_id: Mapped[str | None] = mapped_column(String(40), index=True, default=None)       # future folders
    parent_note_id: Mapped[str | None] = mapped_column(String(40), default=None)              # future version history

    # How the note came to exist. Reused across every creation path.
    # blank | document | summary | chat | selection
    source: Mapped[str] = mapped_column(String(20), nullable=False, default="blank")
    # For AI notes, which template was used (quick|study|detailed|chapterwise|concept|revision).
    note_type: Mapped[str | None] = mapped_column(String(20), default=None)

    title: Mapped[str] = mapped_column(String(300), nullable=False, default="Untitled note")
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")   # canonical editable body (Markdown)
    editor_format: Mapped[str] = mapped_column(String(20), nullable=False, default="markdown")

    # Async generation lifecycle (only meaningful for AI notes; manual notes are born "ready").
    status: Mapped[str] = mapped_column(String(20), index=True, nullable=False, default="ready")
    # ready | queued | processing | completed | failed | cancelled  (manual notes: ready/completed)
    progress: Mapped[int] = mapped_column(Integer, nullable=False, default=100)
    stage: Mapped[str] = mapped_column(String(60), nullable=False, default="ready")
    error: Mapped[str | None] = mapped_column(Text, default=None)

    created_by: Mapped[str] = mapped_column(String(20), nullable=False, default="user")  # user | ai

    # Organization flags.
    is_pinned: Mapped[bool] = mapped_column(Boolean, index=True, nullable=False, default=False)
    is_favorite: Mapped[bool] = mapped_column(Boolean, index=True, nullable=False, default=False)
    is_archived: Mapped[bool] = mapped_column(Boolean, index=True, nullable=False, default=False)

    # Reading telemetry (recomputed on every content write; cheap).
    word_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    reading_time: Mapped[int] = mapped_column(Integer, nullable=False, default=0)   # whole minutes
    section_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    citation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Provenance / telemetry for AI generation.
    model_name: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    prompt_version: Mapped[str] = mapped_column(String(40), nullable=False, default="v1")
    token_usage: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    generation_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Optimistic-concurrency + versioning. `version` increments on every persisted content change
    # so autosave can detect a stale client (conflict → 409) and future history can snapshot.
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    last_opened_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )

    __table_args__ = (
        # Every list query filters by (owner, workspace); the dashboard sorts by these.
        Index("ix_notes_owner_ws", "owner_id", "workspace_id"),
        Index("ix_notes_ws_updated", "workspace_id", "updated_at"),
        # Pinned/favorite fast-paths for the dashboard rails.
        Index("ix_notes_ws_pinned", "workspace_id", "is_pinned"),
    )


class NoteSection(Base):
    __tablename__ = "note_sections"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_sec_id)
    note_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    heading: Mapped[str] = mapped_column(String(300), nullable=False, default="")
    order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")
    citation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    __table_args__ = (Index("ix_note_sections_note_order", "note_id", "order"),)


class NoteCitation(Base):
    __tablename__ = "note_citations"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_cit_id)
    note_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    # Optional link to the generating section (for outline grouping); NULL after content edits.
    note_section_id: Mapped[str | None] = mapped_column(String(40), index=True, default=None)

    document_id: Mapped[str | None] = mapped_column(String(40), default=None)   # vector id (Module-3 /by-vector)
    chunk_id: Mapped[str | None] = mapped_column(String(80), default=None)
    page_number: Mapped[int | None] = mapped_column(Integer, default=None)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    citation_text: Mapped[str] = mapped_column(Text, nullable=False, default="")
    confidence: Mapped[float | None] = mapped_column(Float, default=None)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)


class Tag(Base):
    __tablename__ = "tags"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_tag_id)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    owner_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(60), nullable=False)
    color: Mapped[str] = mapped_column(String(20), nullable=False, default="#6366f1")
    note_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)  # denormalized usage

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)

    __table_args__ = (
        # A tag name is unique per (owner, workspace) — no duplicate labels in a workspace.
        UniqueConstraint("workspace_id", "owner_id", "name", name="uq_tag_ws_owner_name"),
        Index("ix_tags_ws_owner", "workspace_id", "owner_id"),
    )


class NoteTag(Base):
    __tablename__ = "note_tags"

    note_id: Mapped[str] = mapped_column(String(40), primary_key=True)
    tag_id: Mapped[str] = mapped_column(String(40), primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)

    __table_args__ = (Index("ix_note_tags_tag", "tag_id"),)
