"""Flashcard ORM models — Phase 3, Module 7: AI Flashcards & Active Recall Learning Engine.

Four NEW tables (created by `create_all`, no migration — additive, consistent with the rest of the
young schema):

- `Deck`             — a named container of flashcards (workspace-scoped). Also carries the async
                       generation lifecycle when a deck is AI-generated from a source.
- `Flashcard`        — one card + its full Spaced-Repetition (SRS) state. This is the learning
                       asset: persistent, scheduled, citation-aware.
- `FlashcardCitation`— grounded provenance for a card (Workspace → Document → Page → Chunk).
- `FlashcardReview`  — one immutable review event (rating + resulting schedule). The append-only
                       log that powers learning analytics (accuracy, retention, streaks).

Design mirrors the notes/summaries modules: structured rows in SQLite, evidence/vectors in FAISS.
AI cards are generated by REUSING the retrieval + context pipeline (never by feeding whole
documents to the LLM), so every generated card carries the citations Phase 2 preserved.

The SRS state lives ON the Flashcard row (ease_factor, interval_days, next_review_at, …) so the
review queue is a single indexed query (`next_review_at <= now`). The scheduling math is a pure
function in `scheduler.py` — the model only stores its outputs.

Future-proofing (columns present, features NOT implemented): shared/collaborative decks
(`owner_id`, `is_public`), multimedia cards (`media` JSON), AI-tutor mode (`card_type` is
extensible; `MULTIPLE_CHOICE`/`IMAGE`/`DIAGRAM` reserved), version history (not modeled yet).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _deck_id() -> str:
    return f"deck_{uuid.uuid4().hex[:16]}"


def _card_id() -> str:
    return f"card_{uuid.uuid4().hex[:16]}"


def _cit_id() -> str:
    return f"fcit_{uuid.uuid4().hex[:16]}"


def _rev_id() -> str:
    return f"rev_{uuid.uuid4().hex[:16]}"


class Deck(Base):
    __tablename__ = "decks"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_deck_id)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    owner_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    name: Mapped[str] = mapped_column(String(200), nullable=False, default="Untitled deck")
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    color: Mapped[str] = mapped_column(String(20), nullable=False, default="#6366f1")
    icon: Mapped[str] = mapped_column(String(40), nullable=False, default="🎴")

    # Provenance / generation scope (all nullable — a manual deck has none).
    scope: Mapped[str] = mapped_column(String(20), nullable=False, default="manual")  # manual|document|multi|workspace
    document_id: Mapped[str | None] = mapped_column(String(40), index=True, default=None)
    document_ids: Mapped[list | None] = mapped_column(JSON, default=None)
    note_id: Mapped[str | None] = mapped_column(String(40), default=None)
    summary_id: Mapped[str | None] = mapped_column(String(40), default=None)
    conversation_id: Mapped[str | None] = mapped_column(String(40), default=None)
    subject: Mapped[str | None] = mapped_column(String(300), default=None)   # focus hint / seed text
    card_type_pref: Mapped[str] = mapped_column(String(20), nullable=False, default="mixed")
    target_count: Mapped[int] = mapped_column(Integer, nullable=False, default=15)  # cards to generate

    # Async generation lifecycle (only meaningful while an AI batch runs; manual decks are `ready`).
    status: Mapped[str] = mapped_column(String(20), index=True, nullable=False, default="ready")
    # ready | queued | processing | completed | failed | cancelled
    progress: Mapped[int] = mapped_column(Integer, nullable=False, default=100)
    stage: Mapped[str] = mapped_column(String(60), nullable=False, default="ready")
    error: Mapped[str | None] = mapped_column(Text, default=None)

    created_by: Mapped[str] = mapped_column(String(20), nullable=False, default="user")  # user | ai

    card_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)  # denormalized
    is_archived: Mapped[bool] = mapped_column(Boolean, index=True, nullable=False, default=False)
    is_public: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)  # future: shared decks

    # AI telemetry.
    model_name: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    token_usage: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    generation_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )

    __table_args__ = (
        Index("ix_decks_owner_ws", "owner_id", "workspace_id"),
        Index("ix_decks_ws_updated", "workspace_id", "updated_at"),
    )


class Flashcard(Base):
    __tablename__ = "flashcards"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_card_id)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    owner_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    deck_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    # Provenance / back-links.
    document_id: Mapped[str | None] = mapped_column(String(40), index=True, default=None)
    note_id: Mapped[str | None] = mapped_column(String(40), default=None)
    summary_id: Mapped[str | None] = mapped_column(String(40), default=None)
    conversation_id: Mapped[str | None] = mapped_column(String(40), default=None)

    # Content.
    front: Mapped[str] = mapped_column(Text, nullable=False, default="")
    back: Mapped[str] = mapped_column(Text, nullable=False, default="")
    hint: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # basic | definition | cloze | truefalse | (future) multiple_choice | image | diagram
    card_type: Mapped[str] = mapped_column(String(20), nullable=False, default="basic")
    # Cloze answer / TF answer / MCQ options live here (extensible without new columns).
    extra: Mapped[dict | None] = mapped_column(JSON, default=None)
    media: Mapped[dict | None] = mapped_column(JSON, default=None)  # future multimedia
    difficulty: Mapped[str] = mapped_column(String(20), nullable=False, default="medium")  # easy|medium|hard (authoring)

    created_by: Mapped[str] = mapped_column(String(20), nullable=False, default="user")  # user | ai
    status: Mapped[str] = mapped_column(String(20), index=True, nullable=False, default="active")  # active|suspended|archived
    is_favorite: Mapped[bool] = mapped_column(Boolean, index=True, nullable=False, default=False)

    # --- Spaced-Repetition state (outputs of scheduler.py; see that file for the algorithm) ---
    # SM-2 "learning stage": new → learning → review → relearning (after a lapse).
    learning_stage: Mapped[str] = mapped_column(String(20), nullable=False, default="new")
    ease_factor: Mapped[float] = mapped_column(Float, nullable=False, default=2.5)     # SM-2 EF (>= 1.3)
    interval_days: Mapped[int] = mapped_column(Integer, nullable=False, default=0)      # current interval
    repetitions: Mapped[int] = mapped_column(Integer, nullable=False, default=0)        # consecutive successes
    review_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)       # total reviews
    lapse_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)        # times forgotten
    correct_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)      # successful reviews
    mastery_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)    # 0..1 (analytics)
    last_reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    # NULL next_review_at => a brand-new card that has never been scheduled (always "due" as new).
    next_review_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True, default=None)

    citation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )

    __table_args__ = (
        Index("ix_flashcards_deck_status", "deck_id", "status"),
        # The review-queue query: due cards in a workspace/deck ordered by next_review_at.
        Index("ix_flashcards_ws_due", "workspace_id", "status", "next_review_at"),
        Index("ix_flashcards_owner_ws", "owner_id", "workspace_id"),
    )


class FlashcardCitation(Base):
    __tablename__ = "flashcard_citations"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_cit_id)
    flashcard_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    document_id: Mapped[str | None] = mapped_column(String(40), default=None)   # vector id (Module-3 /by-vector)
    chunk_id: Mapped[str | None] = mapped_column(String(80), default=None)
    page_number: Mapped[int | None] = mapped_column(Integer, default=None)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    citation_text: Mapped[str] = mapped_column(Text, nullable=False, default="")
    confidence: Mapped[float | None] = mapped_column(Float, default=None)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)


class FlashcardReview(Base):
    __tablename__ = "flashcard_reviews"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_rev_id)
    flashcard_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    deck_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    owner_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    rating: Mapped[str] = mapped_column(String(10), nullable=False)          # again|hard|good|easy
    quality_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)  # mapped SM-2 quality 0..5
    response_time_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    was_correct: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Schedule snapshot (post-review), for analytics + auditing the SRS.
    prev_interval: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    scheduled_interval: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    ease_factor: Mapped[float] = mapped_column(Float, nullable=False, default=2.5)

    review_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, default=_now, nullable=False)

    __table_args__ = (
        Index("ix_reviews_ws_date", "workspace_id", "review_date"),
        Index("ix_reviews_card_date", "flashcard_id", "review_date"),
    )
