"""Summary ORM models — Phase 3, Module 5: AI Summaries Engine.

Three NEW tables (created by `create_all`, no migration):

- `Summary`          — a persistent, grounded summary of a document / selection / workspace.
- `SummarySection`   — one heading + body block of a summary (ordered).
- `SummaryCitation`  — grounded provenance for a section (Workspace → Document → Page → Chunk).

Design mirrors the chat module: structured rows in SQLite, evidence/vectors in FAISS. A summary
is generated by REUSING the retrieval + context pipeline (never by feeding whole documents to the
LLM), so every section carries the citations Phase 2 preserved.

Future-proofing (columns present, features NOT implemented): version history (`version`,
`parent_summary_id`), multilingual (`language`), multiple generations (each regenerate replaces
sections in place; `version` bumps), collaborative editing (`owner_id` is real).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, DateTime, Float, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _sum_id() -> str:
    return f"sum_{uuid.uuid4().hex[:16]}"


def _sec_id() -> str:
    return f"sec_{uuid.uuid4().hex[:16]}"


def _cit_id() -> str:
    return f"scit_{uuid.uuid4().hex[:16]}"


class Summary(Base):
    __tablename__ = "summaries"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_sum_id)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    owner_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    # Scope of the summary. Exactly one is meaningful per `scope`.
    scope: Mapped[str] = mapped_column(String(20), nullable=False, default="document")  # document|multi|workspace
    document_id: Mapped[str | None] = mapped_column(String(40), index=True, default=None)     # single-doc
    document_ids: Mapped[list | None] = mapped_column(JSON, default=None)                      # multi-doc
    conversation_id: Mapped[str | None] = mapped_column(String(40), default=None)              # summarize-a-chat (future)

    title: Mapped[str] = mapped_column(String(300), nullable=False, default="Untitled summary")
    summary_type: Mapped[str] = mapped_column(String(20), nullable=False, default="standard")
    language: Mapped[str] = mapped_column(String(20), nullable=False, default="en")

    # Async lifecycle (background generation).
    status: Mapped[str] = mapped_column(String(20), index=True, nullable=False, default="queued")  # queued|processing|completed|failed|cancelled
    progress: Mapped[int] = mapped_column(Integer, nullable=False, default=0)  # 0..100
    stage: Mapped[str] = mapped_column(String(60), nullable=False, default="queued")
    error: Mapped[str | None] = mapped_column(Text, default=None)

    # Provenance / telemetry.
    model_name: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    prompt_version: Mapped[str] = mapped_column(String(40), nullable=False, default="v1")
    token_usage: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    generation_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)  # generation_time
    section_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Versioning future-proofing.
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    parent_summary_id: Mapped[str | None] = mapped_column(String(40), default=None)

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )

    __table_args__ = (
        Index("ix_summaries_owner_ws", "owner_id", "workspace_id"),
        Index("ix_summaries_ws_created", "workspace_id", "created_at"),
    )


class SummarySection(Base):
    __tablename__ = "summary_sections"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_sec_id)
    summary_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    heading: Mapped[str] = mapped_column(String(300), nullable=False, default="")
    order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")
    citation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    __table_args__ = (Index("ix_sections_summary_order", "summary_id", "order"),)


class SummaryCitation(Base):
    __tablename__ = "summary_citations"

    id: Mapped[str] = mapped_column(String(40), primary_key=True, default=_cit_id)
    summary_section_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)

    document_id: Mapped[str | None] = mapped_column(String(40), default=None)   # vector id (Module-3 /by-vector)
    chunk_id: Mapped[str | None] = mapped_column(String(80), default=None)
    page_number: Mapped[int | None] = mapped_column(Integer, default=None)
    workspace_id: Mapped[str] = mapped_column(String(40), index=True, nullable=False)
    citation_text: Mapped[str] = mapped_column(Text, nullable=False, default="")
    confidence: Mapped[float | None] = mapped_column(Float, default=None)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
